import { BadRequestException, Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

const BASE = 'https://api.goaffpro.com/v1/admin';

export interface GoAffProAffiliate {
  id: number;
  name?: string;
  email?: string;
  ref_code?: string;
  coupon?: { code?: string };
  status?: string;
}

@Injectable()
export class GoAffProAdapter {
  private readonly logger = new Logger(GoAffProAdapter.name);
  constructor(private readonly config: ConfigService) {}

  get configured() { return Boolean(this.config.get<string>('GOAFFPRO_ACCESS_TOKEN')); }

  private headers() {
    return {
      'X-GOAFFPRO-ACCESS-TOKEN': this.config.get<string>('GOAFFPRO_ACCESS_TOKEN') ?? '',
      'Content-Type': 'application/json'
    };
  }

  private async req<T>(path: string, init?: RequestInit): Promise<T> {
    const res = await fetch(`${BASE}${path}`, { ...init, headers: { ...this.headers(), ...(init?.headers ?? {}) } });
    const json = await res.json().catch(() => ({}));
    if (!res.ok) {
      this.logger.error(`GoAffPro ${path} ${res.status}: ${JSON.stringify(json)}`);
      throw new BadRequestException((json as any)?.message ?? `Error GoAffPro ${res.status}`);
    }
    return json as T;
  }

  /** Find an existing affiliate by email (avoid duplicates). */
  async findByEmail(email: string): Promise<GoAffProAffiliate | null> {
    if (!email) return null;
    const data = await this.req<{ affiliates: GoAffProAffiliate[] }>(
      `/affiliates?fields=id,name,email,ref_code,coupon,status&search=${encodeURIComponent(email)}&limit=5`
    );
    return (data.affiliates ?? []).find((a) => (a.email ?? '').toLowerCase() === email.toLowerCase()) ?? null;
  }

  /** Create an affiliate; GoAffPro auto-generates ref_code + referral coupon. */
  async createAffiliate(input: { name: string; email: string; refCode?: string }): Promise<GoAffProAffiliate> {
    if (!this.configured) throw new BadRequestException('GoAffPro no configurado');
    const body: Record<string, any> = { name: input.name, email: input.email, status: 'approved' };
    if (input.refCode) body.ref_code = input.refCode.toUpperCase().replace(/[^A-Z0-9]/g, '');
    const created = await this.req<GoAffProAffiliate>('/affiliates', { method: 'POST', body: JSON.stringify(body) });
    return created;
  }

  /** Ensure affiliate exists (by email) or create one. Returns id + referral code. */
  async ensureAffiliate(input: { name: string; email: string; refCode?: string }): Promise<{ id: number; code: string; referralUrl: string }> {
    if (!input.email) throw new BadRequestException('Email requerido para crear el código de referido');
    let affiliate = await this.findByEmail(input.email);
    if (!affiliate) affiliate = await this.createAffiliate(input);
    const code = affiliate.coupon?.code ?? affiliate.ref_code ?? '';
    const shopDomain = this.config.get<string>('GOAFFPRO_SHOP_DOMAIN') ?? 'speedwear.es';
    return {
      id: affiliate.id,
      code,
      referralUrl: code ? `https://${shopDomain}/?ref=${encodeURIComponent(affiliate.ref_code ?? code)}` : `https://${shopDomain}`
    };
  }

  /** Affiliate performance: orders + sales generated by their code. */
  async performance(affiliateId: number) {
    const data = await this.req<any>(`/affiliates/${affiliateId}?fields=id,name,ref_code,coupon,orders_count,sales_total,referrals,sales,commission`);
    return {
      ordersCount: Number(data.orders_count ?? data.referrals ?? 0),
      salesTotal: Number(data.sales_total ?? data.sales ?? 0),
      commission: Number(data.commission ?? 0),
      code: data.coupon?.code ?? data.ref_code ?? null
    };
  }
}
